CC = gcc
DEFS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE -D_POSIX_C_SOURCE=200809L
CFLAGS = -Wall -O3 -pg -std=c99 -pedantic $(DEFS)

.PHONY: all clean custom
all: knn clean_after
custom: knn clean_after

knn: knn.o util.o
	$(CC) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

util.o: util.c util.h

clean_after:
	rm -rf *.o

clean:
	rm -rf *.o knn
